services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: host
    volumes:
      - ~/docker/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  model-puller:
    image: curlimages/curl:latest
    container_name: puller
    network_mode: host
    depends_on:
      - ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 10;
      echo 'Stahuji modely pro 1050Ti (Ubuntu)...';
      curl -X POST http://localhost:11434/api/pull -d '{\"name\": \"llama3.2:1b\"}';
      echo 'Hotovo!';
      "
